version: "3"
services:
  appdb:
    image: postgres:10
    container_name: "todo-db"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - TZ=Asia/Tokyo
    ports:
      - "15432:5432"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    driver: local
