name: Github Actions Test CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1
        id: asdf
      - name: Setup node ${{ steps.asdf.outputs.nodejs }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.asdf.outputs.nodejs }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test
        run: npm run test -- --watchAll=false
